######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 18 16:55:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += spreadsheet.qrc
