######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 18 16:57:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h
SOURCES += gotocelldialog.cpp main.cpp
